//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsdh) DeepCopyInto(out *AzureVMSchedulerStartsdh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsdh.
func (in *AzureVMSchedulerStartsdh) DeepCopy() *AzureVMSchedulerStartsdh {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsdh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartsdh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsdhList) DeepCopyInto(out *AzureVMSchedulerStartsdhList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStartsdh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsdhList.
func (in *AzureVMSchedulerStartsdhList) DeepCopy() *AzureVMSchedulerStartsdhList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsdhList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartsdhList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsdhSpec) DeepCopyInto(out *AzureVMSchedulerStartsdhSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsdhSpec.
func (in *AzureVMSchedulerStartsdhSpec) DeepCopy() *AzureVMSchedulerStartsdhSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsdhSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsdhStatus) DeepCopyInto(out *AzureVMSchedulerStartsdhStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsdhStatus.
func (in *AzureVMSchedulerStartsdhStatus) DeepCopy() *AzureVMSchedulerStartsdhStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsdhStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsdh) DeepCopyInto(out *AzureVMSchedulerStopsdh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsdh.
func (in *AzureVMSchedulerStopsdh) DeepCopy() *AzureVMSchedulerStopsdh {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsdh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopsdh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsdhList) DeepCopyInto(out *AzureVMSchedulerStopsdhList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStopsdh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsdhList.
func (in *AzureVMSchedulerStopsdhList) DeepCopy() *AzureVMSchedulerStopsdhList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsdhList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopsdhList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsdhSpec) DeepCopyInto(out *AzureVMSchedulerStopsdhSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsdhSpec.
func (in *AzureVMSchedulerStopsdhSpec) DeepCopy() *AzureVMSchedulerStopsdhSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsdhSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsdhStatus) DeepCopyInto(out *AzureVMSchedulerStopsdhStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsdhStatus.
func (in *AzureVMSchedulerStopsdhStatus) DeepCopy() *AzureVMSchedulerStopsdhStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsdhStatus)
	in.DeepCopyInto(out)
	return out
}
