# permissions for end users to edit awsvmschedulerstartsdhs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsvmschedulerstartsdh-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-sdh
    app.kubernetes.io/part-of: vm-scheduler-operator-sdh
    app.kubernetes.io/managed-by: kustomize
  name: awsvmschedulerstartsdh-editor-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsdhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsdhs/status
  verbs:
  - get
