# permissions for end users to view azurevmschedulerstopsdhs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azurevmschedulerstopsdh-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-sdh
    app.kubernetes.io/part-of: vm-scheduler-operator-sdh
    app.kubernetes.io/managed-by: kustomize
  name: azurevmschedulerstopsdh-viewer-role
rules:
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstopsdhs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstopsdhs/status
  verbs:
  - get
