# permissions for end users to view gcpvmschedulerstopsdhs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gcpvmschedulerstopsdh-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-sdh
    app.kubernetes.io/part-of: vm-scheduler-operator-sdh
    app.kubernetes.io/managed-by: kustomize
  name: gcpvmschedulerstopsdh-viewer-role
rules:
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstopsdhs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstopsdhs/status
  verbs:
  - get
