---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsdhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsdhs/finalizers
  verbs:
  - update
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsdhs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstopsdhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstopsdhs/finalizers
  verbs:
  - update
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstopsdhs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstartsdhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstartsdhs/finalizers
  verbs:
  - update
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstartsdhs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstopsdhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstopsdhs/finalizers
  verbs:
  - update
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstopsdhs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartsdhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartsdhs/finalizers
  verbs:
  - update
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartsdhs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstopsdhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstopsdhs/finalizers
  verbs:
  - update
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstopsdhs/status
  verbs:
  - get
  - patch
  - update
