apiVersion: aws.xyzcompany.com/v1
kind: AWSVMSchedulerStartsdh
metadata:
  labels:
    app.kubernetes.io/name: awsvmschedulerstartsdh
    app.kubernetes.io/instance: awsvmschedulerstartsdh-sample
    app.kubernetes.io/part-of: vm-scheduler-operator-sdh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vm-scheduler-operator-sdh
  name: awsvmschedulerstartsdh-sample
spec:
  # TODO(user): Add fields here
  # Provide image name
  image: "quay.io/manoj_dhanorkar/awsvmscheduler:v1.0"
  
  # Provide comma separated list of AWS instance ids which will be scheduled by CR 
  instanceIds: "i-0757acca253eb77ea"


  # Schedule period for the CronJob.
  # This spec allow you to setup the stop schedule for VM
  # Default: "0 18 * * *" # every weekday at 6 PM
  startSchedule: "* * * * 1-5"
