//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdh) DeepCopyInto(out *AWSVMSchedulerStartsdh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdh.
func (in *AWSVMSchedulerStartsdh) DeepCopy() *AWSVMSchedulerStartsdh {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartsdh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdhList) DeepCopyInto(out *AWSVMSchedulerStartsdhList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStartsdh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdhList.
func (in *AWSVMSchedulerStartsdhList) DeepCopy() *AWSVMSchedulerStartsdhList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdhList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartsdhList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdhSpec) DeepCopyInto(out *AWSVMSchedulerStartsdhSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdhSpec.
func (in *AWSVMSchedulerStartsdhSpec) DeepCopy() *AWSVMSchedulerStartsdhSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdhSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdhStatus) DeepCopyInto(out *AWSVMSchedulerStartsdhStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdhStatus.
func (in *AWSVMSchedulerStartsdhStatus) DeepCopy() *AWSVMSchedulerStartsdhStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdhStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdh) DeepCopyInto(out *AWSVMSchedulerStopsdh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdh.
func (in *AWSVMSchedulerStopsdh) DeepCopy() *AWSVMSchedulerStopsdh {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopsdh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdhList) DeepCopyInto(out *AWSVMSchedulerStopsdhList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStopsdh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdhList.
func (in *AWSVMSchedulerStopsdhList) DeepCopy() *AWSVMSchedulerStopsdhList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdhList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopsdhList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdhSpec) DeepCopyInto(out *AWSVMSchedulerStopsdhSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdhSpec.
func (in *AWSVMSchedulerStopsdhSpec) DeepCopy() *AWSVMSchedulerStopsdhSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdhSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdhStatus) DeepCopyInto(out *AWSVMSchedulerStopsdhStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdhStatus.
func (in *AWSVMSchedulerStopsdhStatus) DeepCopy() *AWSVMSchedulerStopsdhStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdhStatus)
	in.DeepCopyInto(out)
	return out
}
