//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdh) DeepCopyInto(out *GCPVMSchedulerStartsdh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdh.
func (in *GCPVMSchedulerStartsdh) DeepCopy() *GCPVMSchedulerStartsdh {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartsdh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdhList) DeepCopyInto(out *GCPVMSchedulerStartsdhList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStartsdh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdhList.
func (in *GCPVMSchedulerStartsdhList) DeepCopy() *GCPVMSchedulerStartsdhList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdhList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartsdhList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdhSpec) DeepCopyInto(out *GCPVMSchedulerStartsdhSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdhSpec.
func (in *GCPVMSchedulerStartsdhSpec) DeepCopy() *GCPVMSchedulerStartsdhSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdhSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdhStatus) DeepCopyInto(out *GCPVMSchedulerStartsdhStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdhStatus.
func (in *GCPVMSchedulerStartsdhStatus) DeepCopy() *GCPVMSchedulerStartsdhStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdhStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdh) DeepCopyInto(out *GCPVMSchedulerStopsdh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdh.
func (in *GCPVMSchedulerStopsdh) DeepCopy() *GCPVMSchedulerStopsdh {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopsdh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdhList) DeepCopyInto(out *GCPVMSchedulerStopsdhList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStopsdh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdhList.
func (in *GCPVMSchedulerStopsdhList) DeepCopy() *GCPVMSchedulerStopsdhList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdhList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopsdhList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdhSpec) DeepCopyInto(out *GCPVMSchedulerStopsdhSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdhSpec.
func (in *GCPVMSchedulerStopsdhSpec) DeepCopy() *GCPVMSchedulerStopsdhSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdhSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdhStatus) DeepCopyInto(out *GCPVMSchedulerStopsdhStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdhStatus.
func (in *GCPVMSchedulerStopsdhStatus) DeepCopy() *GCPVMSchedulerStopsdhStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdhStatus)
	in.DeepCopyInto(out)
	return out
}
